version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1033
      MONGO_INITDB_DATABASE: webfluxDB
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


  app:
    build: .
    container_name: companies-and-products-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:1033@mongo:27017/webfluxDB?authSource=admin

volumes:
  mongo_data:
    driver: local
